### PR TITLE
Feature/main page

### PR DESCRIPTION
**Pull request by AleksandarDzambas**

### CODE REVIEW

**Comment by Alb9ert** [comment]
ser umiddelbart trash ud

**Review by EmilLykke — APPROVED** [review]
ok

**Review by OliverKjaer — APPROVED** [review]
Great job

**Comment by Shafesadiq** [comment]
NIce, approved.

**Review by Shafesadiq — APPROVED** [review]
nice

**Comment by RasmusJensen1** [comment]
snildt

**Review by RasmusJensen1 — APPROVED** [review]

**Pull request merged**
